<template>
  <v-container>
    <v-card :title="sucess == true ? 'Bienvenido' : 'Login'">
      <v-row justify="center">
        <v-col cols="12" md="6">
          <v-form ref="form" class="mb-4">
            <div v-if="sucess == false">
              <v-text-field v-model="email" label="Email"></v-text-field>
              <v-text-field v-model="password" label="password"></v-text-field>
              <v-row justify="center" class="mb-4">
                <v-btn @click="loginEmail" variant="outlined">
                  <v-icon>mdi-email</v-icon> Login</v-btn
                >
              </v-row>
              <v-row justify="center" class="mb-4">
                <v-btn @click="loginGoogle" variant="outlined">
                  <v-icon color="red">mdi-google</v-icon> Login google</v-btn
                >
              </v-row>
              <v-row justify="center" class="mb-4">
                <v-btn @click="loginFacebbok" variant="outlined">
                  <v-icon color="blue">mdi-facebook</v-icon> Login
                  Facebbok</v-btn
                >
              </v-row>
            </div>
            <div v-else>
              <v-container>
                <span class="display-1"> Hola {{ userLogged.displayName }}</span
                ><br />
                <span class="display-1"> {{ userLogged.email }}</span>
                <br />

                <v-img
                  class="rounded"
                  alt="rounded"
                  :aspect-ratio="16 / 9"
                  :src="userLogged.photoURL"
                >
                </v-img>
                <br />

                <v-row justify="center" class="mb-4">
                  <v-btn @click="logout" variant="outlined"> logout</v-btn>
                </v-row>
              </v-container>
            </div>
            <div>
              <v-alert v-if="sucess" type="info">{{ text }}</v-alert>
              <v-alert v-else type="error">{{ text }}</v-alert>
            </div>
          </v-form>
        </v-col>
      </v-row>
    </v-card>
  </v-container>
</template>

<script lang="ts" setup>
import { ref, Ref } from "vue";
import AuthService from "../services/AuthService";
import {
  getAuth,
  signInWithPopup,
  signInWithEmailAndPassword,
  GoogleAuthProvider,
  FacebookAuthProvider,
} from "firebase/auth";
// Generated by https://quicktype.io

export interface Data {
  uid: string;
  email: string;
  emailVerified: boolean;
  displayName: string;
  isAnonymous: boolean;
  photoURL: string;
  providerData: User[];
  stsTokenManager: StsTokenManager;
  createdAt: string;
  lastLoginAt: string;
  apiKey: string;
  appName: string;
}

export interface User {
  providerId: string;
  uid: string;
  displayName: string;
  email: string;
  phoneNumber: null;
  photoURL: string;
}

export interface StsTokenManager {
  refreshToken: string;
  accessToken: string;
  expirationTime: number;
}

let email = ref("");
let password = ref("");
let sucess = ref(false);
let text = ref("");
let userLogged = ref<Data>([]);
const logout = () => {
  email.value = "";
  password.value = "";
  sucess.value = false;
};
const loginEmail = async () => {
  const auth = getAuth();
  signInWithEmailAndPassword(auth, email.value, password.value)
    .then(() => {
      sucess.value = true;
      text.value = "logueado";
    })
    .catch((error) => {
      text.value = error.message;
      sucess.value = false;
    });
};
const loginGoogle = async () => {
  const provider = new GoogleAuthProvider();
  const auth = getAuth();
  signInWithPopup(auth, provider)
    .then((result) => {
      // This gives you a Google Access Token. You can use it to access the Google API.
      const credential = GoogleAuthProvider.credentialFromResult(result);

      // The signed-in user info.
      const user = result.user;
      console.log(user);
      sucess.value = true;
      text.value = "logueado";
      userLogged.value = user;
      // ...
    })
    .catch((error) => {
      // Handle Errors here.
      const errorCode = error.code;
      const errorMessage = error.message;
      // The email of the user's account used.
      const email = error.customData.email;
      // The AuthCredential type that was used.
      const credential = GoogleAuthProvider.credentialFromError(error);
      text.value = error.message;
      sucess.value = false;

      // ...
    });
};

const loginFacebbok = async () => {
  const provider = new FacebookAuthProvider();
  const auth = getAuth();
  signInWithPopup(auth, provider)
    .then((result) => {
      // This gives you a Google Access Token. You can use it to access the Google API.
      const credential = FacebookAuthProvider.credentialFromResult(result);
      const accessToken = credential.accessToken;
      console.log(credential);
      // The signed-in user info.
      //  const user = result.user;
      // console.log(user);
      sucess.value = true;
      text.value = "logueado";
      //userLogged.value = user;
      // ...
    })
    .catch((error) => {
      // Handle Errors here.
      const errorCode = error.code;
      const errorMessage = error.message;
      // The email of the user's account used.
      const email = error.customData.email;
      // The AuthCredential type that was used.
      const credential = GoogleAuthProvider.credentialFromError(error);
      text.value = error.message;
      sucess.value = false;

      // ...
    });
};
</script>

<style></style>
